### ISSUE TITLE
请问这里是不是不支持moc3模型？

### ISSUE THREAD

**Issue by wjt2018** [luotianyi-saas/wp-libre-live2d#1]

**Comment by baobao1270** [comment]
您好！
本项目的模型解析和动作部分沿用了上游的代码，未做修改。您可以向上游反馈或询问相关问题：

 - https://github.com/panpeihui/Poilive2d
 - https://github.com/unsignedzhang/luotianyi-live2d
 - https://github.com/Dreamer-Paul/Pio

本项目不会增加新的功能，仅做 bug 修复，也无法回答上游负责的问题。
